specVersion: 0.2.0
name: astar-evm
version: 0.0.1
description: This SubQuery project can be use as a starting point for Astar network
repository: https://github.com/subquery/astar-subql-starters
schema:
  file: ./schema.graphql
network:
  endpoint: wss://astar.api.onfinality.io/public-wss
  genesisHash: '0x9eb76c5184c4ab8679d2d5d819fdf90b9c001403e9e17da2e14b6d8aec4029c6'
  # dictionary: https://api.subquery.network/sq/subquery/astar-dictionary
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Moonbeam
    startBlock: 1379519 # block number contracts were deployed

    assets:
      agreement:
        file: './abi/agreement.abi.json'
    processor:
      file: './node_modules/@subql/contract-processors/dist/moonbeam.js'
      options:
        abi: agreement
        # Agreement proxy contract
        address: '0x44EA7Cdc85c6bB9c60c15FF3E21D2c2b9B0df25A'

    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleCreateAgreement
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              # - Transfer(address indexed from,address indexed to,uint256 value)
              # - Attest(address indexed _to,uint256 indexed _tokenId)
              - CreateAgreement(address indexed moderator,bytes32 indexed agreementId)
        # - handler: handleEVMCall
        #   kind: substrate/MoonbeamCall
